package cli

import (
	"io"
)

// GenerateBashCompletion writes bash completion script to the writer.
// This is a placeholder that Task 18 will wire into cobra's built-in
// completion generation.
func GenerateBashCompletion(w io.Writer) error {
	_, err := io.WriteString(w, "# dbx bash completion — generated by `dbx completion bash`\n")
	return err
}

// GenerateZshCompletion writes zsh completion script to the writer.
func GenerateZshCompletion(w io.Writer) error {
	_, err := io.WriteString(w, "# dbx zsh completion — generated by `dbx completion zsh`\n")
	return err
}

// GenerateFishCompletion writes fish completion script to the writer.
func GenerateFishCompletion(w io.Writer) error {
	_, err := io.WriteString(w, "# dbx fish completion — generated by `dbx completion fish`\n")
	return err
}
